dist: trusty
sudo: required

services:
  - docker

env:
  global:
    - RELEASE_VERSION=1.0.0-beta.4

  matrix:
    - DISTRO=centos
      VERSION=7

    - DISTRO=ubuntu
      VERSION=trusty

    - DISTRO=ubuntu
      VERSION=wily

    - DISTRO=ubuntu
      VERSION=xenial

    - DISTRO=debian
      VERSION=jessie

script:
  - chmod +x test.sh
  - ./test.sh $DISTRO $VERSION "$RELEASE_VERSION"
